suppressPackageStartupMessages({
  library(DESeq2)
  library(SummarizedExperiment)
  library(tidyverse)
})

set.seed(42)

# ==============================================================================
# 1. Synthetic Dataset Generation (Unnormalized Counts)
# ==============================================================================

n_genes <- 1000
n_samples <- 6

# Generate baseline Poisson counts across genes
counts_matrix <- matrix(
  rpois(n_genes * n_samples, lambda = 100),
  nrow = n_genes,
  ncol = n_samples,
  dimnames = list(
    paste0("GENE_", sprintf("%04d", 1:n_genes)),
    paste0("SAMPLE_", 1:n_samples)
  )
)

# Inject true differential expression into the first 100 genes for Treated group
counts_matrix[1:100, 4:6] <- as.integer(counts_matrix[1:100, 4:6] * runif(100, 2.5, 5.0))

# Sample metadata
col_data <- DataFrame(
  condition = factor(rep(c("Control", "Treated"), each = 3)),
  batch     = factor(rep(c("B1", "B2", "B1"), times = 2)),
  row.names = colnames(counts_matrix)
)

# ==============================================================================
# 2. Constructing DESeqDataSet & Pre-Filtering
# ==============================================================================

# Build DESeqDataSet directly from count matrix and metadata
dds <- DESeqDataSetFromMatrix(
  countData = counts_matrix,
  colData   = col_data,
  design    = ~condition
)

# Pre-filter low count genes (at least 10 reads across all samples)
keep_genes <- rowSums(counts(dds)) >= 10
dds <- dds[keep_genes, ]

cat("--- Pre-Filtered DESeqDataSet Dimensions ---\n")
print(dim(dds))

# Explicitly lock the reference level for statistical contrasts
dds$condition <- relevel(dds$condition, ref = "Control")

# ==============================================================================
# 3. Running DESeq2 Analysis Pipeline
# ==============================================================================

# Executing size factor estimation, dispersion estimation, and GLM fitting
dds <- DESeq(dds)

# Inspect size factors generated by median-of-ratios normalization
cat("\nEstimated Size Factors per Sample:\n")
print(sizeFactors(dds))

# ==============================================================================
# 4. Extracting Results & Applying LFC Shrinkage
# ==============================================================================

# Extract standard Wald test results for Treated vs Control at FDR threshold 0.05
res_raw <- results(dds, contrast = c("condition", "Treated", "Control"), alpha = 0.05)

cat("\n--- Raw Differential Expression Summary ---\n")
summary(res_raw)

# Apply Log2 Fold Change Shrinkage (normal / apeglm) to penalize noisy low-count genes
res_shrunk <- lfcShrink(
  dds = dds,
  contrast = c("condition", "Treated", "Control"),
  type = "normal"
)

# Convert results into a tidy data frame
de_results_df <- as.data.frame(res_shrunk) %>%
  rownames_to_column(var = "gene_id") %>%
  drop_na(padj) %>%
  arrange(padj)

cat("\nTop 5 Differentially Expressed Genes:\n")
print(head(de_results_df, 5))


# ===============================================================================
# 5. Visualization of Results
# ==============================================================================

# Ensure ggrepel is loaded for smart text positioning
if (!requireNamespace("ggrepel", quietly = TRUE)) install.packages("ggrepel")
library(ggrepel)
library(ggplot2)
library(dplyr)

# 1. Classify genes and flag the top 5 for labeling
plot_data <- de_results_df %>%
  mutate(
    status = case_when(
      log2FoldChange >= 1 & padj < 0.05 ~ "Up-regulated",
      log2FoldChange <= -1 & padj < 0.05 ~ "Down-regulated",
      TRUE ~ "Not Significant"
    ),
    # Create a column that only contains names for the top 5 genes
    label_gene = if_else(gene_id %in% head(de_results_df$gene_id, 5), gene_id, "")
  )

# 2. Build the enhanced plot
p_volcano_enhanced <- ggplot(plot_data, aes(x = log2FoldChange, y = -log10(padj))) +
  # Background points
  geom_point(aes(color = status), alpha = 0.6, size = 2) +
  scale_color_manual(values = c(
    "Up-regulated" = "#E41A1C",
    "Down-regulated" = "#377EB8",
    "Not Significant" = "#999999"
  )) +

  # CRITICAL FEATURE 1: Significance Cutoff Grid Lines
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "darkgray", linewidth = 0.6) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "darkgray", linewidth = 0.6) +

  # CRITICAL FEATURE 2: Smart Gene Labels
  geom_text_repel(
    aes(label = label_gene),
    size = 4,
    fontface = "bold",
    box.padding = 0.5,
    point.padding = 0.3,
    segment.color = "black",
    max.overlaps = Inf
  ) +

  # Styling and clean layout
  theme_classic() +
  labs(
    title = "Volcano Plot: Differential Gene Expression",
    subtitle = "Treated vs Control (Top 5 labeled; Thresholds: |LFC| > 1, padj < 0.05)",
    x = "Log2 Fold Change",
    y = "-Log10 Adjusted P-value (padj)",
    color = "Expression Status"
  ) +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    legend.position = "right"
  )

# 3. Render and export the plot
print(p_volcano_enhanced)
ggsave("deseq2_volcano_plot.pdf", plot = p_volcano_enhanced, width = 8, height = 6)
